# Environment-specific Service Accounts for DEV with IRSA
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vote
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::792373136340:role/vote3-dev-vote-irsa"
  labels:
    app.kubernetes.io/name: vote
    app.kubernetes.io/part-of: vote3
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: result
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::792373136340:role/vote3-dev-result-irsa"
  labels:
    app.kubernetes.io/name: result
    app.kubernetes.io/part-of: vote3
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: worker
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::792373136340:role/vote3-dev-worker-irsa"
  labels:
    app.kubernetes.io/name: worker
    app.kubernetes.io/part-of: vote3
