# ConfigMap - Values will be populated by bootstrap workflow after Terraform
apiVersion: v1
kind: ConfigMap
metadata:
  name: voteapp-demo1-config
data:
  REDIS_HOST: "PLACEHOLDER_REDIS_HOST"
  DATABASE_HOST: "PLACEHOLDER_DATABASE_HOST"
  DATABASE_SECRET_ARN: "PLACEHOLDER_SECRET_ARN"
  DATABASE_NAME: "votes"
  AWS_REGION: "us-west-2"
